-- Diplaying categories with most trending videos 

SELECT 
CATEGORY_TITLE,
COUNT(VIDEO_ID) AS TRENDING_VIDEOS
FROM  TABLE_YOUTUBE_FINAL
WHERE CATEGORY_TITLE NOT IN ('Entertainment','Music')
GROUP BY CATEGORY_TITLE
ORDER BY 2 DESC; 

-- Displaying categories with most trending videos in various counttries

SELECT *
FROM
	(SELECT 
	 COUNTRY,
	 CATEGORY_TITLE,
	 COUNT(VIDEO_ID) AS TRENDING_VIDEOS,
	 RANK() OVER (PARTITION BY COUNTRY ORDER BY COUNT(VIDEO_ID) DESC) AS RK
	FROM 
	TABLE_YOUTUBE_FINAL
	WHERE CATEGORY_TITLE NOT IN ('Entertainment','Music')
	GROUP BY COUNTRY,CATEGORY_TITLE)
WHERE RK <=1 
ORDER BY COUNTRY,TRENDING_VIDEOS DESC;