SELECT * FROM 
(
	SELECT COUNTRY, TITLE, CHANNELTITLE, VIEW_COUNT,
	ROW_NUMBER() OVER (PARTITION BY COUNTRY ORDER BY VIEW_COUNT DESC) AS RK
	FROM
	TABLE_YOUTUBE_FINAL
    WHERE CATEGORY_TITLE = 'Sports' AND TRENDING_DATE = '2021-10-17'
    )
WHERE RK <4;