CREATE OR REPLACE TABLE TABLE_YOUTUBE_DUPLICATES
AS
SELECT A.ID,A.VIDEO_ID, A.TITLE,A.PUBLISHEDAT,A.CHANNEL_ID,A.CHANNELTITLE,A.CATEGORYID, A.ROWNUMBER
FROM
(
    SELECT 
    ID,
    VIDEO_ID, 
    TITLE,
    PUBLISHEDAT,
    CHANNEL_ID,
    CHANNELTITLE,
    CATEGORYID,
    CATEGORY_TITLE,
    TRENDING_DATE,     
    VIEW_COUNT,
    LIKES,
    DISLIKES,
    COMMENT_COUNT,
    COMMENT_DISABLED,
    COUNTRY,
    ROW_NUMBER() OVER (PARTITION BY VIDEO_ID,TRENDING_DATE, COUNTRY
                       ORDER BY VIEW_COUNT) ROWNUMBER                   
    FROM TABLE_YOUTUBE_FINAL) A
WHERE A.ROWNUMBER > 1;