SELECT COUNTRY, YEAR_MONTH, TITLE, CHANNELTITLE, CATEGORY_TITLE, VIEW_COUNT,
ROUND(AVG(LIKES/VIEW_COUNT)*100,2) AS RATIO
    FROM 
    (   
        SELECT COUNTRY,
        TO_CHAR (PUBLISHEDAT,'YYYY-MM')||'-01' AS YEAR_MONTH,
        TITLE, 
        CHANNELTITLE, 
        LIKES,
        CATEGORY_TITLE, 
        VIEW_COUNT,
        ROW_NUMBER() OVER (PARTITION BY COUNTRY, YEAR_MONTH ORDER BY VIEW_COUNT DESC) RK
        FROM
        TABLE_YOUTUBE_FINAL
    )
WHERE RK = 1 
GROUP BY COUNTRY,YEAR_MONTH, TITLE, CHANNELTITLE, CATEGORY_TITLE, VIEW_COUNT
ORDER BY YEAR_MONTH,COUNTRY;